CREATE TABLE `question` (
    `question_id` int(10) unsigned auto_increment,
    `user_id` int(10) unsigned default null,
    `name` varchar(255) default null,
    `subject` varchar(255) not null,
    `message` text,
    `ip` varchar(45) default null,
    `views` int(10) unsigned NOT NULL DEFAULT '0',
    `views_browser` int(10) unsigned NOT NULL DEFAULT '0',
    `created` datetime NOT NULL,
    `created_datetime` datetime NOT NULL,
    `created_name` varchar(255) default null,
    `created_ip` varchar(45) default null,
    `modified_datetime` DATETIME DEFAULT NULL,
    `modified_user_id` INT(10) UNSIGNED DEFAULT NULL,
    `deleted` datetime default null,
    `deleted_datetime` datetime default null,
    `deleted_user_id` int(10) default null,
    `deleted_reason` varchar(255) default null,
    PRIMARY KEY (`question_id`),
    KEY `user_id` (`user_id`),
    KEY `subject_deleted_views_browser` (`subject`, `deleted`, `views_browser`),
    KEY `ip` (`ip`),
    KEY `created_deleted_views` (`created`, `deleted`, `views`),
    KEY `created_deleted_views_browser` (`created`, `deleted`, `views_browser`),
    KEY `created_datetime_deleted` (`created_datetime`, `deleted`),
    KEY `created_name_deleted_created_datetime` (`created_name`, `deleted`, `created_datetime`),
    KEY `created_name_deleted_views_browser` (`created_name`, `deleted`, `views_browser`),
    KEY `created_ip_created_datetime` (`created_ip`, `created_datetime`),
    KEY `deleted_created_datetime` (`deleted`, `created_datetime`),
    KEY `deleted_user_id_deleted` (`deleted_user_id`, `deleted`)
) CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
